### ISSUE TITLE
error: attribute 'defaultApp.x86_64-linux' should have type 'derivation'

### ISSUE THREAD

**Issue by davidak** [vlinkz/nixos-conf-editor#11]
[davidak@gaming:~]$ nix run github:vlinkz/nixos-conf-editor
error: attribute 'defaultApp.x86_64-linux' should have type 'derivation'

NixOS 22.11.2606.2fb7d749c08

Also reported at https://discourse.nixos.org/t/nixos-conf-editor-a-gtk4-libadwaita-configuration-editor/19426/5?u=davidak

**Comment by vlinkz** [comment]
I've updated the flake.nix file to hopefully fix this issue

**Comment by davidak** [comment]
I still get the same issue with the command.
