### ISSUE TITLE
Location dialog not usable

### ISSUE THREAD

**Issue by davidak** [vlinkz/nixos-conf-editor#2]
I see this in terminal when i open the location selection:

> If you handle this event, you must return
> `GDK_EVENT_PROPAGATE` so the default handler
> gets the event as well

I can click around, but nothing happens.

![Screenshot from 2022-06-02 01-44-56](https://user-images.githubusercontent.com/91113/171519337-5309b0db-bd50-437d-b0b9-8d61211b7895.png)

**Comment by vlinkz** [comment]
Hm, so far I've only tested it on GNOME, so could be I need to modify something or add a dependency, thanks for the issue!

**Comment by Zahrun** [comment]
Works fine in KDE

**Comment by davidak** [comment]
I also don't have this issue anymore.

i can select a file and don't get any output in terminal.
