### ISSUE TITLE
feature request: filter to view only changed values

### ISSUE THREAD

**Issue by magnetophon** [vlinkz/nixos-conf-editor#6]
Thanks for this wonderful project, I'm looking forward to be able to recommend NixOS (or snowflakeOS) to my non-nerd friends!

**Comment by vlinkz** [comment]
Great idea!! Added a basic implementation in d38f5336a58feb318d9ed549b4f56ed8791fc083
![Screenshot from 2022-09-28 13-54-34](https://user-images.githubusercontent.com/20145996/192854711-b5d22fc4-4865-429d-b6ab-cfc4f2491f6a.png)

**Comment by magnetophon** [comment]
I just tried this, and it only shows me a small selection of the options I configured.
How can I help troubleshoot this?

**Comment by vlinkz** [comment]
Right now it shows only options that you have set in your configuration.nix or modified in the editor. Is it not doing that or did I misunderstand the request?

**Comment by magnetophon** [comment]
I haven't changed anything in the editor, but it is showing only a small part of [my configuration.nix](https://github.com/magnetophon/nixosConfig/blob/master/machines/nix14/default.nix).

While looking up the above link, I noticed the exact problem: it is picking up the changes from my configuration.nix, but not from the [imports](https://github.com/magnetophon/nixosConfig/blob/master/machines/nix14/default.nix#L3).

**Comment by vlinkz** [comment]
Right now modifying only a single configuration is supported. I made a new issue to track this here: #7

**Comment by magnetophon** [comment]
OK, thanks.
